# Generated by Django 3.2.8 on 2022-01-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211127_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='polyline',
        ),
        migrations.CreateModel(
            name='PositionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positionGroup', to='main.polyline')),
            ],
        ),
        migrations.AddField(
            model_name='positions',
            name='posGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.positiongroup'),
        ),
    ]
