# Generated by Django 3.2.8 on 2022-01-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220111_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiongroup',
            options={'verbose_name': 'Позиция группа', 'verbose_name_plural': 'Позициялар группа'},
        ),
    ]
