# Generated by Django 3.2.8 on 2022-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220111_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polylineroad',
            name='beton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Асфальт'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='goodSituation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='жақсы шқ.'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='hectar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гектар'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='shagal_tas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Шағал тас'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='topirak',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Топырак'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ені'),
        ),
        migrations.AlterField(
            model_name='polylineroad',
            name='yearConstruction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Салынған жылы '),
        ),
    ]
