# Generated by Django 3.2.8 on 2022-01-14 18:07

import city.newFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_auto_20220113_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitieswater',
            name='currentQ',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жаңартылып жатқаны (2021-2022ж)'),
        ),
        migrations.AddField(
            model_name='localitieswater',
            name='nysan',
            field=models.TextField(blank=True, null=True, verbose_name='2022ж ағымдағы жөндеуден өтетін  су құбырлары мен нысандары (ш.қ)'),
        ),
        migrations.AddField(
            model_name='localitieswater',
            name='zaramdyQ',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жарамды құбырлар  (ш.қ)'),
        ),
    ]
