# Generated by Django 3.2.8 on 2022-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_auto_20220114_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitieswater',
            name='diametress',
            field=models.ManyToManyField(related_name='localitiesWater', to='city.Diametr', verbose_name='Диаметры'),
        ),
    ]
