# Generated by Django 3.2.8 on 2022-01-25 09:16

import city.newFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0014_auto_20220124_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitiesgas',
            name='jGasLength',
            field=city.newFields.BCharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitiesgas',
            name='oGasLength',
            field=city.newFields.BCharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitiesgas',
            name='tomenKysym',
            field=city.newFields.BCharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
