# Generated by Django 3.2.8 on 2022-01-13 18:13

import city.newFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_auto_20220111_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitieswater',
            name='waterMatersDontCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Су есептегіш құралдары орнатылмаған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='needToUpdate',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жаңартуды қажет ететіні (км) '),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='newPipes',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жаңартылған құбырлар (км)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='newYearConstruction',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Жаңартылған жылы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='populationCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Халық саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='springSource',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Бұлақ көзі'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='streetCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Көше саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='subscribersCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Абонент саны '),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='wateMetersCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Су есептегіш құралдары орнатылған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterDebit',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Судың дебеті'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Су құбырының ұзындығы (км)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterReserves',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жер асты су қоры хаттамасы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterStructure',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Су құбырының құрылымы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='yearConstruction',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Салынған жылы'),
        ),
    ]
