# Generated by Django 3.2.8 on 2022-01-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_alter_localitieswater_nysan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitieswater',
            name='currentQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жаңартылып жатқаны (2021-2022ж)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='diametress',
            field=models.ManyToManyField(default=1, related_name='localitiesWater', to='city.Diametr', verbose_name='Диаметры'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='localities',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localitiesWater', to='city.localities', verbose_name='Елді мекен'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='needToUpdate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жаңартуды қажет ететіні (км) '),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='newPipes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жаңартылған құбырлар (км)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='newYearConstruction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жаңартылған жылы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='nysan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2022ж ағымдағы жөндеуден өтетін  су құбырлары мен нысандары (ш.қ)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='populationCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Халық саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='springSource',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бұлақ көзі'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='streetCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Көше саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='subscribersCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Абонент саны '),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='wateMetersCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Су есептегіш құралдары орнатылған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterDebit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Судың дебеті'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterLength',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Су құбырының ұзындығы (км)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterMatersDontCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Су есептегіш құралдары орнатылмаған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterReserves',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жер асты су қоры хаттамасы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterStructure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Су құбырының құрылымы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='yearConstruction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Салынған жылы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='zaramdyQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жарамды құбырлар  (ш.қ)'),
        ),
    ]
