# Generated by Django 3.2.8 on 2022-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_alter_localitieswater_nysan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitieswater',
            name='newYearConstruction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жаңартылған жылы'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='populationCount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Халық саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='streetCount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Көше саны'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='subscribersCount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Абонент саны '),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='wateMetersCount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Су есептегіш құралдары орнатылған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='waterMatersDontCount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Су есептегіш құралдары орнатылмаған (саны)'),
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='yearConstruction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Салынған жылы'),
        ),
    ]
