# Generated by Django 3.2.8 on 2022-01-24 20:10

import city.newFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_alter_localitieswater_diametress'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitieselectr',
            name='trCOM',
            field=city.newFields.BIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitieselectr',
            name='trOJT',
            field=city.newFields.BIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localitieswater',
            name='diametress',
            field=models.ManyToManyField(blank=True, related_name='localitiesWater', to='city.Diametr', verbose_name='Диаметры'),
        ),
    ]
