# Generated by Django 3.2.8 on 2022-03-18 11:36

import city.newFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0017_auto_20220125_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitieselectr',
            name='aCOM',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Ағаш Комуналдық меншік'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='aOJT',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Ағаш ОЖТ меншігінде'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='aOZ',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Ағаш Өздері орнатқан '),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='bCOM',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Бағаналар Комуналдық меншік'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='bOJT',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Бағаналар ОЖТ меншігінде'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='bOZ',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Бағаналар Өздері орнатқан '),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='baganaNumber',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Бағаналардың жалпы саны (дана)'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='cipCOM',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='СИП Комуналдық меншік'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='cipLength',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='CIP жалпы ұзындығы'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='cipOJT',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='СИП ОЖТ меншігінде'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='cipOZ',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='СИП Өздері орнатқан'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='length',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Электр жүйесінің ұзындығы '),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='tmOCOM',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Темір электр Комуналдық меншік'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='tmOJT',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Темір электр ОЖТ меншігінде'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='tmOOZ',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Темір Өздері орнатқан'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trCOM',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Коммуналдық меншікте'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trCip',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='СИП кабель ВЛ-06 кВт (метр)'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trNumber',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Трансформатор (КТПН)  саны '),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trOJT',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Трансформатор ОЖТ меншігінде'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trVl',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='ВЛ-04 кВт (метр)'),
        ),
        migrations.AlterField(
            model_name='localitieselectr',
            name='trbaganaNumber',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Трансформатордағы бағаналардың жалпы саны (дана)'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='bottomGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жер асты газ құбырлары (метр)'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='gasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Газ  құбыры жүйесінің ұзындығы'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='grpsh',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='ГРПШ-6 саны'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='jGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жоғары қысымды газ құбырлары (ш.қ (км))'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='oGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Орта қысымды газ құбырлары (ш.қ (км))'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='populationCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Халық саны'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='subscribersCount',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Абонент саны '),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='tomenKysym',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Төмен қысымды құбырлар'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='topGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Жер үсті газ құбырлары (метр)'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='typeGas',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Құбырлардың құрылымы'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='volumeGas',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Газ тұтыну көлемі '),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='yearConstruction',
            field=city.newFields.BIntegerField(blank=True, null=True, verbose_name='Салынған жылы'),
        ),
    ]
