# Generated by Django 3.2.8 on 2022-03-24 13:23

import city.newFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0018_auto_20220318_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitieselectr',
            name='trVl',
            field=models.FloatField(blank=True, null=True, verbose_name='Тозу пайызы (%)'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='bottomGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Тозығы жеткен құбыр'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='gasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Газ құбыры жүйесінің ұзындығы'),
        ),
        migrations.AlterField(
            model_name='localitiesgas',
            name='topGasLength',
            field=city.newFields.BCharField(blank=True, max_length=255, null=True, verbose_name='Тозуы процент'),
        ),
    ]
